---
title: "Nested Forecaster"
output:
    flexdashboard::flex_dashboard:
        orientation: rows
        theme:
            bg: "#FFFFFF"
            fg: "#2c3e50"
            primary: "#18bc9c"
            base_font: !expr bslib::font_google("Oswald")
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo    = FALSE,
    message = FALSE,
    warning = FALSE
)

library(shiny)
library(shinyjs)
library(plotly)
library(reactable)
library(bslib)

library(modeltime)
library(tidymodels)

library(tidyverse)
library(timetk)

```


```{r}


best_models_tbl <- read_rds("artifacts/best_models_tbl.rds")

indicator_options <- best_models_tbl$item_id

default_options <- indicator_options[1:3]

```



# Product Exploration

## Column {.sidebar}

#### What does it do?

Forecast one or more products within a sales database.

<hr>

#### How it works

```{r}
useShinyjs(rmd = TRUE)
    
shiny::selectInput(
    inputId   = "products",
    label     = "Select Products to Forecast",
    choices   = indicator_options,
    selected  = default_options,
    selectize = TRUE, 
    multiple  = TRUE
)

numericInput(
    inputId = "forecast_horizon", 
    label   = "Forecast Horizon (N)", 
    value   = 90, 
    min     = 2
)

shiny::sliderInput(
    inputId = "conf_interval",
    label   = "Prediction Interval",
    min     = 0, 
    max     = 1, 
    value   = 0.95
)
    
actionButton(inputId = "apply", label = "Apply", icon = icon("play"))

actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))


observeEvent(eventExpr = input$reset, handlerExpr = {
  
    updateSelectInput(
        session  = session, 
        inputId  = "products",
        selected = default_options
    )
    
    updateNumericInput(
        inputId = "forecast_horizon", 
        value   = 90
    )
    
    updateSliderInput(
        session = session, 
        inputId = "conf_interval",
        value   = 0.95
    )
    
  shinyjs::delay(ms = 300, expr = {
      shinyjs::click(id = "apply")
  })
 
  
})


```

<hr>

__Learning Lab 63: Nested Forecasting.__

Based on the 1st Shiny App Project in [Shiny Dashboards Course](https://university.business-science.io/p/ds4b-102-r-shiny-web-application-business-level-1)

Learn more at [Business Science](https://www.business-science.io/)


```{r}
# LOGIC

rv <- reactiveValues()

observeEvent(input$apply, {
    
    rv$model_tbl <- best_models_tbl %>% filter(item_id %in% input$products)
    
    rv$forecast_tbl <- rv$model_tbl %>%
        modeltime_nested_forecast(
            h = input$forecast_horizon,
            conf_interval = input$conf_interval,
            control = control_nested_forecast(
                verbose   = TRUE,
                allow_par = FALSE
            )
        )
    
    
}, ignoreNULL = FALSE)
```


## Row {.tabset .tabset-fade}

### Predicted Forecast (Next N-Days)

```{r}
output$plotly_1 <- renderPlotly({
    
    facet_col <- 1
    
    if (length(input$products) > 3) facet_col <- 2
    
    if (length(input$products) > 8) facet_col <- 4
    
    rv$forecast_tbl %>%
        group_by(item_id) %>%
        plot_modeltime_forecast(
            .facet_ncol = facet_col, 
            .legend_max_width = 26, 
            .plotly_slider = TRUE
        )
})

plotlyOutput(outputId = "plotly_1")
```


### Test Forecast

```{r}
output$plotly_2 <- renderPlotly({
    
    facet_col <- 1
    
    if (length(input$products) > 3) facet_col <- 2
    
    if (length(input$products) > 8) facet_col <- 4
    
    rv$model_tbl %>%
        extract_nested_test_forecast(.id_subset = input$products) %>%
        group_by(item_id) %>%
        plot_modeltime_forecast(
            .facet_ncol = facet_col, 
            .legend_max_width = 26, 
            .plotly_slider = TRUE
        )
})

plotlyOutput(outputId = "plotly_2")

```

### Test Accuracy

```{r}
output$reactable_1 <- renderReactable({
    rv$model_tbl %>%
        extract_nested_test_accuracy() %>%
        filter(item_id %in% input$products) %>%
        table_modeltime_accuracy()
})

reactableOutput("reactable_1")
```
