# Install packages
devtools::install_github("shrektan/techfactor")
remotes::install_github("curso-r/treesnip@catboost")
remotes::install_github("tidymodels/stacks", ref = "main")
devtools::install_github("stevenpawley/recipeselectors")
devtools::install_github('catboost/catboost', subdir = 'catboost/R-package')

install.packages("gtrendsR")
install.packages("Quandl")
install.packages("quantmod")
install.packages("RcppRoll")
install.packages("tidyquant")
install.packages("tidymodels")
install.packages("tidytext")
install.packages("doParallel")
install.packages("glmnet")
install.packages("FSelectorRcpp")
install.packages("praznik")
install.packages("Boruta")
install.packages("lightgbm")

# Load Packages
library(tidyverse) # install.packages("tidyverse")
library(stringr)
library(gtrendsR)
library(Quandl)
library(quantmod)
library(RcppRoll)
library(lubridate)
library(tidyquant)
library(treesnip) # remotes::install_github("curso-r/treesnip")
library(tidymodels)
library(tsfeatures)
library(slider)
library(timetk)
library(data.table)
library(xts)
library(TTR)
library(PerformanceAnalytics)
library(tidytext)
library(techfactor) # devtools::install_github("shrektan/techfactor")
library(doParallel)
library(catboost) # https://catboost.ai/en/docs/installation/r-installation-local-copy-installation
library(xgboost)
library(workflows)
library(dials)
library(recipeselectors)
library(FSelectorRcpp)
library(praznik)
library(Boruta)
library(stacks)
